name: tiecd
description: Tools for cloud deployments
version: 0.0.1
repository: https://github.com/dataaxiom/tiecd

environment:
  sdk: ^3.1.2

dependencies:
  meta: 1.15.0
  yaml: 3.1.2
  xml: 6.5.0
  args: 2.5.0
  json_annotation: 4.9.0
  checked_yaml: 2.0.3
  uuid: 4.5.0
  path: 1.9.0
  crypto: 3.0.5
  json2yaml: 3.0.1
  posix: 6.0.1
  intl: 0.19.0
  kubernetes: 1.26.0+5
  http: 1.2.2
  io: 1.0.4
  text_analysis: 1.0.0+2

dev_dependencies:
  build_runner: 2.4.12
  flutter_oss_licenses: 3.0.2
  json_serializable: 6.8.0
  lints: 4.0.0
  test: 1.25.8
