schema_version: 1
version: 1.0.0
name: helm
description: "Add the helm utility"
artifacts:
  - name: "helm.tar.gz"
    url: "https://get.helm.sh/helm-v3.14.2-linux-amd64.tar.gz"
    sha256: "0885a501d586c1e949e9b113bf3fb3290b0bbf74db9444a1d8c2723a143006a5"
execute:
  - script: configure
