name: build
run-name: build
on: 
  push:
    branches: [ "*" ]
    tags:
      - "v*"

env:
  FLUTTER_ROOT: dummy

jobs:
  dart-build:
    runs-on: ubuntu-latest
    container:
      image: 'ghcr.io/dataaxiom/dart-linux:latest'
    steps:
    - name: Check out repo
      uses: actions/checkout@v3
    - name: Generate OSS licenses
      run: dart pub run flutter_oss_licenses:generate.dart -o oss_licenses.json --json
    - name: Dart build
      run: dart run build_runner build
    - name: Dart executable build
      run: dart compile exe bin/tiecd.dart -o bin/tiecd
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: |
          bin/tiecd
          oss_licenses.json
        retention-days: 1
  docker-build:
    runs-on: ubuntu-latest
    needs: dart-build
    strategy:
      fail-fast: false
      matrix:
        image: [
          'full', 'k8s', 'okd', 'gke', 'eks', 'jdk8', 'jdk11', 'jdk17', 'jdk21', 'node18', 'node20', 'vercel'
        ]
    steps:
    - name: Check out repo
      uses: actions/checkout@v3
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        name: build-artifacts
    - name: Set exec bit
      run: chmod +x bin/tiecd
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ghcr.io/${{ github.repository_owner }}/tiecd
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Install CEKit
      uses: cekit/actions-setup-cekit@v1.1.5
    - name: Save tags
      run: echo "${{ steps.meta.outputs.tags }}" >> tags.txt
    - name: Build ${{ matrix.image }} Image
      run: scripts/build-image.sh ${{ matrix.image }}
